item {
  id: 1
  name: "Astro Boy"
}
item {
  id: 2
  name: "Bart Simpson"
}
item {
  id: 3
  name: "Batman"
}
item {
  id: 4
  name: "Betty Boop"
}
item {
  id: 5
  name: "Daffy Duck"
}
item {
  id: 6
  name: "Doraemon"
}
item {
  id: 7
  name: "Eric Cartman"
}
item {
  id: 8
  name: "Fa Mulan"
}
item {
  id: 9
  name: "Garfield"
}
item {
  id: 10
  name: "Gon Freecss"
}
item {
  id: 11
  name: "Goofy"
}
item {
  id: 12
  name: "Homer J. Simpson"
}
item {
  id: 13
  name: "Jerry Mouse"
}
item {
  id: 14
  name: "Kakashi"
}
item {
  id: 15
  name: "Kenshiro"
}
item {
  id: 16
  name: "Killua Zoldyck"
}
item {
  id: 17
  name: "Kureyon Shin Chan"
}
item {
  id: 18
  name: "Levi Ackerman"
}
item {
  id: 19
  name: "Mario"
}
item {
  id: 20
  name: "Mickey Mouse"
}
item {
  id: 21
  name: "Mikasa Ackerman"
}
item {
  id: 22
  name: "Naruto"
}
item {
  id: 23
  name: "Sasuke"
}
item {
  id: 24
  name: "Snow White"
}
item {
  id: 25
  name: "Spiderman"
}
item {
  id: 26
  name: "SpongeBob"
}
